/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/models/car.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_1.geometry}
          material={materials["0.952941_0.749020_0.894118_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_2.geometry}
          material={materials["0.070588_0.074510_0.058824_0.000000_0.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_3.geometry}
          material={materials["0.866667_0.321569_0.156863_0.000000_0.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_4.geometry}
          material={materials["0.070588_0.074510_0.058824_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_5.geometry}
          material={materials["0.866667_0.321569_0.156863_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_6.geometry}
          material={materials["0.952941_0.749020_0.894118_0.000000_0.003"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_7.geometry}
          material={materials["0.301961_0.301961_0.301961_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_8.geometry}
          material={materials["0.992157_0.992157_0.992157_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_9.geometry}
          material={materials["0.000000_0.000000_0.000000_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_10.geometry}
          material={materials["0.325490_0.529412_0.752941_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_11.geometry}
          material={materials["1.000000_0.611765_0.023529_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_12.geometry}
          material={materials["1.000000_0.000000_0.000000_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_13.geometry}
          material={materials["0.972549_0.529412_0.003922_0.000000_0.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_14.geometry}
          material={materials["0.086275_0.317647_0.690196_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_15.geometry}
          material={materials["0.854902_0.078431_0.000000_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_16.geometry}
          material={materials["0.917647_0.917647_0.917647_0.000000_0.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Pink_body001_17.geometry}
          material={materials["0.223529_1.000000_0.078431_0.000000_0.001"]}
        />
      </group>
    </group>
  );
}
export default Model;

useGLTF.preload("/car.glb");
